from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Circle1(object):
    def setupUi(self, Circle1):
        Circle1.setObjectName("Circle1")
        Circle1.resize(500, 300)
        self.pushButton_2 = QtWidgets.QPushButton(Circle1)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Circle1)
        self.label.setGeometry(QtCore.QRect(90, 20, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Circle1)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 120, 126, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 10;\n"
"border: 2px solid #505050;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Circle1)
        self.label_2.setGeometry(QtCore.QRect(200, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Circle1)
        self.pushButton.setGeometry(QtCore.QRect(150, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Circle1)
        self.label_5.setGeometry(QtCore.QRect(200, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(Circle1)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 10;\n"
"border: 2px solid #505050;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(Circle1)
        QtCore.QMetaObject.connectSlotsByName(Circle1)

        self.pushButton.clicked.connect(lambda: self.add_functions())

    def retranslateUi(self, Circle1):
        _translate = QtCore.QCoreApplication.translate
        Circle1.setWindowTitle(_translate("Circle1", "Вычисли градусную меру дуг"))
        self.pushButton_2.setText(_translate("Circle1", "вернуться назад"))
        self.label.setText(_translate("Circle1", "От точки O на окружности хорда AB видна под углом N:"))
        self.label_2.setText(_translate("Circle1", "Градус N"))
        self.pushButton.setText(_translate("Circle1", "Дать ответ"))
        self.label_5.setText(_translate("Circle1", "Ответ:"))

    def add_functions(self):
        input_cut1 = float(self.lineEdit_2.text())

        otvet = 360 - (input_cut1 * 2)

        self.lineEdit_4.setText(str(otvet))