from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Square1(object):
    def setupUi(self, Square1):
        Square1.setObjectName("Square1")
        Square1.resize(500, 300)
        self.pushButton_2 = QtWidgets.QPushButton(Square1)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Square1)
        self.label.setGeometry(QtCore.QRect(40, 50, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Square1)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Square1)
        self.label_3.setGeometry(QtCore.QRect(330, 90, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Square1)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 10;\n"
"border: 2px solid #505050;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Square1)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 10;\n"
"border: 2px solid #505050;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(Square1)
        self.pushButton.setGeometry(QtCore.QRect(150, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Square1)
        self.label_4.setGeometry(QtCore.QRect(200, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Square1)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius: 10;\n"
"border: 2px solid #505050;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(Square1)
        QtCore.QMetaObject.connectSlotsByName(Square1)

        self.pushButton.clicked.connect(lambda: self.add_functions())

    def retranslateUi(self, Square1):
        _translate = QtCore.QCoreApplication.translate
        Square1.setWindowTitle(_translate("Square1", "Найти площадь параллелограма"))
        self.pushButton_2.setText(_translate("Square1", "вернуться назад"))
        self.label.setText(_translate("Square1", "Впишите высоту параллелограма и его основание."))
        self.label_2.setText(_translate("Square1", "ОСНОВАНИЕ"))
        self.label_3.setText(_translate("Square1", "ВЫСОТА"))
        self.pushButton.setText(_translate("Square1", "Дать ответ"))
        self.label_4.setText(_translate("Square1", "Ответ:"))

    def add_functions(self):
        input_cut1 = float(self.lineEdit_2.text())
        input_cut2 = float(self.lineEdit_4.text())

        otvet = input_cut1 * input_cut2

        self.lineEdit_3.setText(str(otvet))